development:
   adapter: mysql
   database: music_app_development
   username: root
   password:
   host: localhost

test:
   adapter: mysql
   database: music_app_test
   username: root
   password:
   host: localhost
