# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4b22c44a1f2ac28f47da39443b09785f68499eedd06e00b46f7b45aeb9a0cc4f9faca92e681748018560cbb11c50db27afe624ca4d1ea5d0733e2e347799b5c

test:
  secret_key_base: 0bb66d0df798d75443c6cd772a2eb7b0a9c012da9ead851b1f74c2a962f7fa8afe6616d629f4e4a4dfcf48e1fb50e318c96a8855a069360723e307ba945dbad7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
